"""tes

Revision ID: a4512cbe019e
Revises: 030e7c7ac685
Create Date: 2021-02-12 13:11:47.772688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4512cbe019e'
down_revision = '030e7c7ac685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
